# Getting Started with Arrays in NumPy

In [1]:
import numpy as np

## Creating array from list

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs NumPy Array

In [4]:
py_list = [1,2,3]
print("Python list Multiplication: ", py_list*2)

# Doing same for numpy array
np_array = np.array([1,2,3]) # Element wise multiplication
print("Numpy array multiplication: ", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\nPython list operation time: ", time.time()-start)

start = time.time()
np_array = np.arange(100000)*2
print("Numpy array operation time: ", time.time()-start)

Python list Multiplication:  [1, 2, 3, 1, 2, 3]
Numpy array multiplication:  [2 4 6]

Python list operation time:  0.004137992858886719
Numpy array operation time:  0.0032591819763183594


### Creating array from scratch

In [16]:
# Creating 3x3 0s Matrix
zeros = np.zeros((3,3))
print("\nZeros array: \n", zeros)

# Creating 3x3 1s Matrix
ones = np.ones((3,3))
print("\nOnes array: \n", ones)

# Creating martix of any number
# 3x3 matrix of 5
full = np.full((3,3), 5)
print("\nFull array: \n", full)

# Random number matrix
# 2x3 matrix of random numbers
random = np.random.random((2, 3)) # Random numbers between 0 and 1
random2 = np.random.randint(1, 10, (2,3)) # Random numbers between 1 and 10
print("\nRandom array: \n", random)
print("\nRandom array2: \n", random2)

# Sequences
sequence = np.arange(0, 10, 2) # Start, Stop, Step. By default step is 1 np.array(0, 10)
print("\nSequence array: ", sequence)


Zeros array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Full array: 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

Random array: 
 [[0.06814581 0.22339796 0.0929538 ]
 [0.23720313 0.29195554 0.17402456]]

Random array2: 
 [[2 6 6]
 [4 3 4]]

Sequence array:  [0 2 4 6 8]


### Vector, Matrix and Tensor

In [17]:
# Creating a vector
vetor = np.array([1,2,3])
print("\nVector: ", vetor)

matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print("\nMatrix: \n", matrix)


Vector:  [1 2 3]

Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
