## NumPy Array operations

In [1]:
import numpy as np

In [17]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing: ", arr[2:7])

# Slicing with step
print("Slicing with step: ", arr[2:8:2])

# Negative Indexing
print("Negative Indexing: ", arr[-3:-1])

# Slicing with steps and negative indexing
print("Slicing with steps and negative indexting: ", arr[-6:-1:2])

# Slicing 2D arrays
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

# Specific element
print("Specific element on (1,2): ", arr_2d[1,2]) # row, column = 6

# Targeting a row
print("Targeting a row (2):", arr_2d[2]) # row 2

# Targeting a column
print("Targeting a cloumn (0): ", arr_2d[:,0]) # column 0

Basic slicing:  [3 4 5 6 7]
Slicing with step:  [3 5 7]
Negative Indexing:  [7 8]
Slicing with steps and negative indexting:  [4 6 8]
Specific element on (1,2):  6
Targeting a row (2): [7 8 9]
Targeting a cloumn (0):  [1 4 7]


## Sorting

In [21]:
unsorted = np.array([3,1,5,2,4])
print("Unsorted: ", unsorted)
print("Sorted: ", np.sort(unsorted))

# Sorting 2D arrays
unsorted_2d = np.array([[3,1,5],
                        [2,4,6],
                        [9,7,8]])
print("Unsorted 2D array: ", unsorted_2d)
print("Sorted 2D array by column: ", np.sort(unsorted_2d, axis=0))
print("Sorted 2D array by row: ", np.sort(unsorted_2d, axis=1))

Unsorted:  [3 1 5 2 4]
Sorted:  [1 2 3 4 5]
Unsorted 2D array:  [[3 1 5]
 [2 4 6]
 [9 7 8]]
Sorted 2D array by column:  [[2 1 5]
 [3 4 6]
 [9 7 8]]
Sorted 2D array by row:  [[1 3 5]
 [2 4 6]
 [7 8 9]]


## Filter

In [25]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

# Filtering even numbers:
print("Even numbers: ", numbers[numbers % 2 == 0])

# Filtering odd numbers:
print("Odd numbers: ", numbers[numbers % 2 != 0])

Even numbers:  [ 2  4  6  8 10]
Odd numbers:  [1 3 5 7 9]


## Filter with Mask

In [26]:
mask = numbers > 5
print("Numbers greater than 5: ", numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [ ]:
indices = [0, 2, 4]
print("Indices: ", numbers[indices])

where = np.where(numbers[indices] > 1)
# print(where) => This will display the indices of the elements that are greater than 1
print("Where: ", numbers[where])

Indices:  [1 3 5]
Where:  [2 3]


In [49]:
conditional_array = np.where(numbers > 5, numbers * 2, numbers) # If the number is greater than 5, multiply by 2, else return the number. This is like a ternary operator.
print("Conditional array: ", conditional_array)

Conditional array:  [ 1  2  3  4  5 12 14 16 18 20]


## Adding and removing data

In [51]:
# Merging two arrays
arr = np.array([1,2,3])
arr2 = np.array([4,5,6])

mergedArray = np.concatenate((arr, arr2))
print("Merged Array: ", mergedArray)

Merged Array:  [1 2 3 4 5 6]


## Array Compatibility

In [52]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility shapes: ", a.shape == b.shape)

Compatibility shapes:  True


### Reshaping the array

In [58]:
original = np.array([
    [1,2],
    [3,4]
])

new_row = np.array([5,6])

# Adding new row to the previous original array
with_new_row = np.vstack((original, new_row)) # vstack is used to add a new row (vertical-stack)
print("Original Array: ", original)
print("With new row: ", with_new_row)

new_column = np.array([7,8])
with_new_column = np.hstack((original, new_column.reshape(2,1))) # hstack is used to add a new column (horizontal-stack). Here we also need to reshape the new column to match the original array's shape.
print("Original array: ", original)
print("With new column: ", with_new_column)

# We can also add new column with the following method:
new_column2 = np.array([[7], [8]])
with_new_column2 = np.hstack((original, new_column2))
print("Original array: ", original)
print("With new column 2: ", with_new_column2)

Original Array:  [[1 2]
 [3 4]]
With new row:  [[1 2]
 [3 4]
 [5 6]]
Original array:  [[1 2]
 [3 4]]
With new column:  [[1 2 7]
 [3 4 8]]
Original array:  [[1 2]
 [3 4]]
With new column 2:  [[1 2 7]
 [3 4 8]]


### Deleting row or column

In [64]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 1) # This will delete the element at index 1
print("Array after deletion: ", deleted)

Array after deletion:  [1 3 4 5]
