## Advance Operations with Business examples

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [10]:
# Data structure:  [resturant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000], # Paradise Biryani
    [2, 120000, 140000, 160000, 190000], # Beijing Bites
    [3, 200000, 230000, 260000, 300000], # Pizza Hub
    [4, 180000, 210000, 240000, 270000], # Burger Point
    [5, 160000, 285000, 205000, 230000]  # Chai Point
    ])

print(" === Zomato Sales Analysis === ")

# Get the shape of the data, it is mandatory before processing the data
print("\nSales Data Shape: ", sales_data.shape)

# Data of first three resturants
print("\nSample data for first three resturants:\n", sales_data[:3])

# Get all the data except the first column (resturant_id)
print("\nSample Data except resturant_id:\n", sales_data[:, 1:])

 === Zomato Sales Analysis === 

Sales Data Shape:  (5, 5)

Sample data for first three resturants:
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

Sample Data except resturant_id:
 [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 285000 205000 230000]]


In [14]:
# Total sales per year
print("=== Total Sales per year ===")
total_sales = np.sum(sales_data[:,1:], axis=0) # axis=0 means column wise sum and [:, 1:] means all rows and columns except the first column
print("2021: ", total_sales[0])
print("2022: ", total_sales[1])
print("2023: ", total_sales[2])
print("2024: ", total_sales[3])

=== Total Sales per year ===
2021:  810000
2022:  1045000
2023:  1085000
2024:  1240000


In [17]:
# Total sales per resturant since 2021
print("=== Total Sales per resturant since 2021 ===")
total_sales = np.sum(sales_data[:, 1:], axis=1) # axis=1 means row wise sum and [:, 1:] means all rows and columns except the first column
print("Paradise Biryani: ", total_sales[0])
print("Beijing Bites: ", total_sales[1])
print("Pizza Hub: ", total_sales[2])
print("Burger Point: ", total_sales[3])
print("Chai Point: ", total_sales[4])

=== Total Sales per resturant since 2021 ===
Paradise Biryani:  800000
Beijing Bites:  610000
Pizza Hub:  990000
Burger Point:  900000
Chai Point:  880000


In [ ]:
# Minimum and Maximum sales by individual resturants per year
minimum_sales = np.min(sales_data[:, 1:], axis=1)
maximum_sales = np.max(sales_data[:, 1:], axis=1)
print("Minimum sales by Paradise Biryani since 2021: ", minimum_sales[0])
print("Maximum sales by Paradise Biryani since 2021: ", maximum_sales[0])
print("Minimum sales by Beijing Bites since 2021: ", minimum_sales[1])
print("Maximum sales by Beijing Bites since 2021: ", maximum_sales[1])
print("Minimum sales by Pizza Hub since 2021: ", minimum_sales[2])
print("Maximum sales by Pizza Hub since 2021: ", maximum_sales[2])
print("Minimum sales by Burger Point since 2021: ", minimum_sales[3])
print("Maximum sales by Burger Point since 2021: ", maximum_sales[3])
print("Minimum sales by Chai Point since 2021: ", minimum_sales[4])
print("Maximum sales by Chai Point since 2021: ", maximum_sales[4])

Minimum sales by Paradise Biryani since 2021:  150000
Maximum sales by Paradise Biryani since 2021:  250000
Minimum sales by Beijing Bites since 2021:  120000
Maximum sales by Beijing Bites since 2021:  190000
Minimum sales by Pizza Hub since 2021:  200000
Maximum sales by Pizza Hub since 2021:  300000
Minimum sales by Burger Point since 2021:  180000
Maximum sales by Burger Point since 2021:  270000
Minimum sales by Chai Point since 2021:  160000
Maximum sales by Chai Point since 2021:  285000


In [23]:
# Maximum and Minimum sales per year
max_sales = np.max(sales_data[:, 1:], axis=0)
min_sales = np.min(sales_data[:, 1:], axis=0)
print("Maximum sales in 2021: ", max_sales[0])
print("Minimum sales in 2021: ", min_sales[0])
print("Maximum sales in 2022: ", max_sales[1])
print("Minimum sales in 2022: ", min_sales[1])
print("Maximum sales in 2023: ", max_sales[2])
print("Minimum sales in 2023: ", min_sales[2])
print("Maximum sales in 2024: ", max_sales[3])
print("Minimum sales in 2024: ", min_sales[3])

Maximum sales in 2021:  200000
Minimum sales in 2021:  120000
Maximum sales in 2022:  285000
Minimum sales in 2022:  140000
Maximum sales in 2023:  260000
Minimum sales in 2023:  160000
Maximum sales in 2024:  300000
Minimum sales in 2024:  190000
